language: node_js
node_js:
  - "5"
  - "4"
  - "iojs-v3"
  - "iojs-v2"
  - "iojs-v1"
  - "0.12"

before_install:
  - npm install npm@3 -g
  - npm install codeclimate-test-reporter -g

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: 675d45f71b58f3b5d6c1eb2b7b5e5499098131a0f6225063f3ba52defb90f5b4
